# Site settings
title: Gavin McDowell
description: 'Computer Scientist, Student, Dancer, Musician'
url: ""
baseurl: ""
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Gavin McDowell'
  email: gmmcdow@gmail.com
  twitter_username: gavdarth
  github_username:  gavaga
  linkedin_username:  gavinmcdowell

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'
  -
    scope:
      path: ''
      type: 'projects'
    values:
        layout: 'project'

collections:
  projects:
    output: true
    permalink: /:collection/:name

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
